### ISSUE TITLE
custom data training

### ISSUE THREAD

**Issue by wangjingg** [anonymoussss/YOLOX-SwinTransformer#1]
I want to train pedestrian detector with only one class, it is ready in coco format, how do I need to modify it?

**Comment by anonymoussss** [comment]
My own dataset also contains only one class.
1 preparing the dataset according to the coco format. (√)
2 modify the ‘self.data_dir’, ‘self.train_ann’, and ‘self.val_ann’ in the configuration file (e.g. exps/default/yolox_swinS_coco.py).
3 Make 'train2017' and 'val2017' folders under the 'self.data_dir' path and put the train/val images in them. 
4 Make an 'annotations' folder in the 'self.data_dir' path and place the annotation files in it.

**Comment by wangjingg** [comment]
好的，非常感谢

**Comment by BAp3r** [comment]
> My own dataset also contains only one class. 1 preparing the dataset according to the coco format. (√) 2 modify the ‘self.data_dir’, ‘self.train_ann’, and ‘self.val_ann’ in the configuration file (e.g. exps/default/yolox_swinS_coco.py). 3 Make 'train2017' and 'val2017' folders under the 'self.data_dir' path and put the train/val images in them. 4 Make an 'annotations' folder in the 'self.data_dir' path and place the annotation files in it.

你好，请问你在预训练的时候是否只用了私有数据集
