### ISSUE TITLE
你好我的是VOC数据集，想用S的width和depth，在这报错了

### ISSUE THREAD

**Issue by Chengyunlai** [anonymoussss/YOLOX-SwinTransformer#2]
`        if swin_pretrained:
            assert swin_pretrained_type in ["COCO", "ImageNet"], "swin_pretrained_type should be 'COCO' or 'ImageNet'."
            assert swin_pretrained_checkpoint, "swin_pretrained_checkpoint is not given."
            logger.info("Pretrained type: {}, load swin backbone from {}.".format(swin_pretrained_type, swin_pretrained_checkpoint))
            self.load_pretrained(swin_pretrained_type, swin_pretrained_checkpoint) `

**Comment by anonymoussss** [comment]
这个swin_pretrained_type对应的不是数据集标注格式，是选择使用COCO数据集预训练的backbone还是ImageNet预训练的backbone。这个参数和数据标注格式是json、xml还是txt没有关系，如果你使用VOC格式（xml）的数据集，那么有两种解决方法：第一，把voc格式数据集转成coco格式，github上有很多转化代码。第二，yolox官方库有voc格式的exp文件，copy来然后把yolox-swin独有的参数加进去就行了。推荐第一种解决方法。

**Comment by Chengyunlai** [comment]
哦哦，好的，谢谢你！:+1:
